ARG IMAGE
FROM docker.io/library/$IMAGE
MAINTAINER Seo Sanghyeon <sanxiyn@gmail.com>

WORKDIR /root
RUN apt update \
    && DEBIAN_FRONTEND=noninteractive apt install -y tzdata \
    && apt install -y --no-install-recommends \
        ca-certificates \
        cmake \
        curl \
        gcc \
        git \
        libc-dev \
        libssl-dev \
        make \
        pkgconf
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | \
    sh -s -- -y --default-toolchain none --no-modify-path
ENV PATH=/root/.cargo/bin:$PATH
RUN rustup toolchain install --profile minimal --component rustc-codegen-cranelift -- nightly-2024-03-17
RUN git clone --branch main --depth 1 https://github.com/Byron/gitoxide.git
WORKDIR /root/gitoxide
RUN RUSTC_TARGET=$(rustc -vV | grep host: | cut -d ' ' -f 2) \
    && cargo fetch --target $RUSTC_TARGET
