[package]
name = "hn-downloader"
version = "0.0.1"
authors = ["Seo Sanghyeon <sanxiyn@gmail.com>"]
edition = "2021"

[dependencies]
clap = "2"
futures = "0.3"
indicatif = "0.17"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
