[package]
name = "print-uslm-sections"
version = "0.0.1"
authors = ["Seo Sanghyeon <sanxiyn@gmail.com>"]
edition = "2021"

[dependencies]
argparse = "0.2"
quick-xml = ">=0.24.1"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
