[package]
name = "lobsters-search"
version = "0.0.1"
authors = ["Seo Sanghyeon <sanxiyn@gmail.com>"]
edition = "2021"

[dependencies]
clap = "2"
reqwest = { version = "0.11", features = ["blocking"] }
select = "0.6"
url = "2"
